# Basic
title: 章凯
subtitle: 小白程序员
welcome_message: <a href="https://github.com/K-ZeFeng" target="_blank">我的github</a>
description: 博客记录点滴知识.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/K-ZeFeng'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: https://weibo.com/2647787452/profile?topnav=1&wvr=6&is_all=1
    github: https://github.com/K-ZeFeng
    twitter: onevcat
    gplus: 107108267983477358170
    mail: 2247376155@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
